steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rfp-data-enricher:latest', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run','deploy','rfp-data-enricher',
        '--image','gcr.io/$PROJECT_ID/rfp-data-enricher:latest',
        '--region','us-central1',
        '--allow-unauthenticated',
        '--set-secrets','OPENAI_API_KEY=OPENAI_API_KEY:latest',
        '--set-env-vars','PROJECT_ID=$PROJECT_ID,DATASET_ID=rfpdata,TABLE=OUTPUT,BQ_LOCATION=europe-southwest1,OPENAI_MODEL=gpt-4o-mini,STOP_ON_GPT_QUOTA=1',
        '--max-instances','1','--concurrency','1','--min-instances','1'
      ]
images:
  - 'gcr.io/$PROJECT_ID/rfp-data-enricher:latest'
