name: Build & Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: rfp-database-464609
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build & push Docker image
      id: build
      run: |
        IMAGE="gcr.io/rfp-database-464609/data-enricher:${{ github.sha }}"
        gcloud builds submit --tag "$IMAGE" .
        echo "image=$IMAGE" >> $GITHUB_OUTPUT

    - name: Deploy to Cloud Run
      run: |
        IMAGE="${{ steps.build.outputs.image }}"
        gcloud run deploy data-enricher \
          --image "$IMAGE" \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars \
PROJECT_ID=rfp-database-464609,DATASET_ID=rfpdata,RAW_TABLE=performing_arts_raw,STAGING_TABLE=performing_arts_enriched_staging,OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
